### ISSUE TITLE
Change Menu Options

### ISSUE THREAD

**Issue by ghost** [sudharti/socify#46]
When logged in, how can i move the newsfeed and other links to the left side under avatar icon vs being on the right? Also how can I make a drop down menu or add more options to nav bar?

**Comment by scaffeinate** [comment]
@jrenna100 You would need to fix the layout in order to bring the left links onto to the right. Checkout the the layout in this https://github.com/scaffeinate/socify/blob/master/app/views/home/index.html.erb. Refer bootstrap grid to see how the layout works: http://getbootstrap.com/css/#grid

Also for the navbar you can add items in the _navbar.html.erb partial under views/shared. https://github.com/scaffeinate/socify/blob/master/app/views/shared/_navbar.html.erb

**Comment by ghost** [comment]
gotcha check email
